In [2]:
import numpy as np

# Примеры создания массивов

## Создание массива из списка

In [3]:
a = np.array([1,1,2,3,5,8]) # Создание массива из списка
a

array([1, 1, 2, 3, 5, 8])

In [4]:
type(a) # Тип массива

numpy.ndarray

In [5]:
a.shape # Форма массива

(6,)

In [6]:
a2 = np.array([[1,2,3], # Создание двумерного массива
              [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

## *Создание* массива при помощи фукнций

In [7]:
b = np.eye(5) # Создание единичной матрицы
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
c = np.empty(10) # Создание массива без инициализации значений
for i in range(10): # Заполнение массива последовательностью Фибоначчи
    if i == 0 or i == 1:
        c[i] = 1
    else:
        c[i] = c[i-1] + c[i-2]
c

array([ 1.,  1.,  2.,  3.,  5.,  8., 13., 21., 34., 55.])

# Примеры индексирования и срезов

## Индексирование массива

In [10]:
e = np.arange(0, 100, 4)
e[11] # Вывод элемента номер 12

np.int64(44)

In [11]:
a2[1][2] # Вывод 3ьего элемента 2о строки массива а2

np.int64(6)

## Срез

In [12]:
e[9:20] # Срез с 10 по 20 элемент

array([36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76])

In [13]:
e[9:20:2] # Срез с 10 по 20 элемент с шагом 2

array([36, 44, 52, 60, 68, 76])

# Примеры векторных операций и базовых статистик

## Сложение и умножение массивов

In [14]:
f = np.ones(5) # Создание одномерного массива из пяти единичек
f

array([1., 1., 1., 1., 1.])

In [15]:
g = np.arange(0, 5, 1) # Создание массива со значениями в диапазоне от 0 до 5 с шагом 1
g

array([0, 1, 2, 3, 4])

In [16]:
f + g # Сложение

array([1., 2., 3., 4., 5.])

In [17]:
f * g # Умножение

array([0., 1., 2., 3., 4.])

In [18]:
h = np.empty(5)
for i in range(5): # Поэлементное умножение массива на числа от 0 до 4 соответственно
    h[i] = g[i] * i
h

array([ 0.,  1.,  4.,  9., 16.])

## Статистика

In [19]:
np.mean(e) # Среднее значение

np.float64(48.0)

In [20]:
np.median(e) # Медиана

np.float64(48.0)

In [21]:
np.std(e) # Стандартное отклонение

np.float64(28.844410203711913)