In [1]:
import numpy as np  # Импорт библиотеки NumPy с общепринятым сокращением

# --- Примеры создания массивов ---

# 1. Из обычных списков
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)
print(f"Массив из списка: {array_from_list}")

# 2. С использованием функций zeros, ones, arange
zeros_array = np.zeros((2, 3))  # Создание массива 2x3, заполненного нулями
print(f"Массив из нулей:\n{zeros_array}")

ones_array = np.ones(4)  # Создание одномерного массива из четырех единиц
print(f"Массив из единиц: {ones_array}")

arange_array = np.arange(0, 10, 2)  # Создание массива от 0 до 9 с шагом 2
print(f"Массив из arange: {arange_array}")

# --- Демонстрация атрибутов ---

# Вывод формы (shape) и типа данных (dtype) для одного из массивов
print(f"\nАтрибуты array_from_list:")
print(f"  Форма (shape): {array_from_list.shape}")  # Количество измерений и элементов в каждом измерении
print(f"  Тип данных (dtype): {array_from_list.dtype}")  # Тип элементов в массиве

# --- Примеры индексирования и срезов ---

my_array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(f"\nИсходный массив для индексирования:\n{my_array}")

# 1. Получение отдельного элемента
element = my_array[1, 2]  # Элемент во второй строке (индекс 1) и третьем столбце (индекс 2)
print(f"Отдельный элемент (my_array[1, 2]): {element}")

# 2. Извлечение подмассива с помощью среза
subarray = my_array[0:2, 1:3]  # Подмассив: строки с 0 по 1, столбцы с 1 по 2
print(f"Подмассив (my_array[0:2, 1:3]):\n{subarray}")

# --- Примеры векторных операций и базовых статистик ---

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(f"\nМассив A: {a}")
print(f"Массив B: {b}")

# 1. Поэлементное сложение массивов
sum_array = a + b
print(f"Поэлементное сложение (A + B): {sum_array}")

# 2. Поэлементное умножение массивов
product_array = a * b
print(f"Поэлементное умножение (A * B): {product_array}")

# 3. Вычисление средней величины (mean) для массива
mean_value = np.mean(a)
print(f"Среднее значение массива A (np.mean(A)): {mean_value}")

# 4. Вычисление суммы элементов массива
sum_all = np.sum(b)
print(f"Сумма всех элементов массива B (np.sum(B)): {sum_all}")

Массив из списка: [1 2 3 4 5]
Массив из нулей:
[[0. 0. 0.]
 [0. 0. 0.]]
Массив из единиц: [1. 1. 1. 1.]
Массив из arange: [0 2 4 6 8]

Атрибуты array_from_list:
  Форма (shape): (5,)
  Тип данных (dtype): int64

Исходный массив для индексирования:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Отдельный элемент (my_array[1, 2]): 60
Подмассив (my_array[0:2, 1:3]):
[[20 30]
 [50 60]]

Массив A: [1 2 3]
Массив B: [4 5 6]
Поэлементное сложение (A + B): [5 7 9]
Поэлементное умножение (A * B): [ 4 10 18]
Среднее значение массива A (np.mean(A)): 2.0
Сумма всех элементов массива B (np.sum(B)): 15
